import { useState } from 'react'

const RESPONSE_COLORS = {
  'No Response': 'bg-gray-100 text-gray-600',
  'Replied': 'bg-green-100 text-green-700',
  'Not Interested': 'bg-red-100 text-red-700',
}

export default function ColdEmails({ emails, addEmail, updateEmail, deleteEmail, addFollowup, followups }) {
  const [showForm, setShowForm] = useState(false)
  const [editId, setEditId] = useState(null)
  const [form, setForm] = useState({
    name: '', company: '', email: '', subject: '', date: '',
    response: 'No Response', notes: '', followUpDays: ''
  })

  function handleChange(e) {
    setForm({ ...form, [e.target.name]: e.target.value })
  }

  async function handleSubmit() {
    if (!form.name || !form.email) return

    if (editId !== null) {
      await updateEmail(editId, form)
      setEditId(null)
    } else {
      await addEmail(form)

      if (form.followUpDays) {
        const baseDate = form.date ? new Date(form.date) : new Date()
        baseDate.setDate(baseDate.getDate() + parseInt(form.followUpDays) + 1)
        const followUpDate = baseDate.toISOString().split('T')[0]

        await addFollowup({
          name: form.name,
          company: form.company,
          contact: form.email,
          followUpDate,
          notes: `Auto follow-up from cold email. Subject: ${form.subject}`,
          done: false,
          autoGenerated: true,
        })
      }
    }

    setForm({
      name: '', company: '', email: '', subject: '', date: '',
      response: 'No Response', notes: '', followUpDays: ''
    })
    setShowForm(false)
  }

  function handleEdit(entry) {
    setForm({
      name: entry.name, company: entry.company, email: entry.email,
      subject: entry.subject, date: entry.date, response: entry.response,
      notes: entry.notes, followUpDays: entry.followUpDays || ''
    })
    setEditId(entry.id)
    setShowForm(true)
  }

  async function handleDelete(id) {
    await deleteEmail(id)
  }

  return (
    <div>
      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-3xl font-bold text-[#0f1724]">Cold Emails</h1>
          <p className="text-gray-500 mt-1 text-sm">Log everyone you've reached out to</p>
        </div>
        <button
          onClick={() => { setShowForm(!showForm); setEditId(null); setForm({ name: '', company: '', email: '', subject: '', date: '', response: 'No Response', notes: '', followUpDays: '' }) }}
          className="bg-[#e8572a] text-white px-5 py-2.5 rounded-lg text-sm font-medium hover:bg-[#cf4a20] transition"
        >
          + Log Email
        </button>
      </div>

      {showForm && (
        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 mb-8">
          <h2 className="text-lg font-semibold text-[#0f1724] mb-4">
            {editId !== null ? 'Edit Entry' : 'New Cold Email'}
          </h2>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="text-xs font-medium text-gray-500 uppercase tracking-wide">Contact Name</label>
              <input
                name="name"
                value={form.name}
                onChange={handleChange}
                placeholder="e.g. Jane Smith"
                className="mt-1 w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#e8572a]"
              />
            </div>
            <div>
              <label className="text-xs font-medium text-gray-500 uppercase tracking-wide">Company</label>
              <input
                name="company"
                value={form.company}
                onChange={handleChange}
                placeholder="e.g. Shopify"
                className="mt-1 w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#e8572a]"
              />
            </div>
            <div>
              <label className="text-xs font-medium text-gray-500 uppercase tracking-wide">Email / LinkedIn</label>
              <input
                name="email"
                value={form.email}
                onChange={handleChange}
                placeholder="e.g. jane@shopify.com or linkedin.com/in/jane"
                className="mt-1 w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#e8572a]"
              />
            </div>
            <div>
              <label className="text-xs font-medium text-gray-500 uppercase tracking-wide">Date Sent</label>
              <input
                name="date"
                type="date"
                value={form.date}
                onChange={handleChange}
                className="mt-1 w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#e8572a]"
              />
            </div>
            <div>
              <label className="text-xs font-medium text-gray-500 uppercase tracking-wide">Subject</label>
              <input
                name="subject"
                value={form.subject}
                onChange={handleChange}
                placeholder="e.g. Exploring opportunities at Shopify"
                className="mt-1 w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#e8572a]"
              />
            </div>
            <div>
              <label className="text-xs font-medium text-gray-500 uppercase tracking-wide">Response</label>
              <select
                name="response"
                value={form.response}
                onChange={handleChange}
                className="mt-1 w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#e8572a]"
              >
                <option>No Response</option>
                <option>Replied</option>
                <option>Not Interested</option>
              </select>
            </div>
            <div>
              <label className="text-xs font-medium text-gray-500 uppercase tracking-wide">Auto Follow-Up After (days)</label>
              <input
                name="followUpDays"
                type="number"
                min="1"
                value={form.followUpDays}
                onChange={handleChange}
                placeholder="e.g. 7"
                className="mt-1 w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#e8572a]"
              />
              <p className="text-xs text-gray-400 mt-1">A follow-up will be auto-created in Follow-Ups</p>
            </div>
            <div>
              <label className="text-xs font-medium text-gray-500 uppercase tracking-wide">Notes</label>
              <textarea
                name="notes"
                value={form.notes}
                onChange={handleChange}
                placeholder="What was the email about? Any context..."
                rows={3}
                className="mt-1 w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#e8572a]"
              />
            </div>
          </div>
          <div className="flex gap-3 mt-4">
            <button
              onClick={handleSubmit}
              className="bg-[#e8572a] text-white px-5 py-2 rounded-lg text-sm font-medium hover:bg-[#cf4a20] transition"
            >
              {editId !== null ? 'Save Changes' : 'Log Email'}
            </button>
            <button
              onClick={() => setShowForm(false)}
              className="border border-gray-200 text-gray-500 px-5 py-2 rounded-lg text-sm hover:bg-gray-50 transition"
            >
              Cancel
            </button>
          </div>
        </div>
      )}

      {emails.length === 0 ? (
        <div className="text-center py-20 text-gray-400">
          <p className="text-lg font-medium">No cold emails logged yet</p>
          <p className="text-sm mt-1">Click "Log Email" to start tracking your outreach</p>
        </div>
      ) : (
        <div className="flex flex-col gap-4">
          {emails.map(entry => (
            <div key={entry.id} className="bg-white rounded-2xl shadow-sm border border-gray-100 p-5 flex items-start justify-between">
              <div>
                <div className="flex items-center gap-3 mb-1">
                  <h3 className="font-semibold text-[#0f1724] text-lg">{entry.name}</h3>
                  <span className={`text-xs font-medium px-2.5 py-0.5 rounded-full ${RESPONSE_COLORS[entry.response]}`}>
                    {entry.response}
                  </span>
                  {entry.followUpDays && (
                    <span className="text-xs font-medium px-2.5 py-0.5 rounded-full bg-orange-50 text-orange-500">
                      Follow-up in {entry.followUpDays}d
                    </span>
                  )}
                </div>
                <p className="text-gray-500 text-sm">{entry.company} · {entry.email}</p>
                {entry.subject && <p className="text-gray-400 text-xs mt-1">Subject: {entry.subject}</p>}
                {entry.date && <p className="text-gray-400 text-xs">Sent: {entry.date}</p>}
                {entry.notes && <p className="text-gray-600 text-sm mt-2 bg-gray-50 rounded-lg px-3 py-2">{entry.notes}</p>}
              </div>
              <div className="flex gap-2 ml-4 shrink-0">
                <button
                  onClick={() => handleEdit(entry)}
                  className="text-xs border border-gray-200 px-3 py-1.5 rounded-lg text-gray-500 hover:bg-gray-50 transition"
                >
                  Edit
                </button>
                <button
                  onClick={() => handleDelete(entry.id)}
                  className="text-xs border border-red-100 px-3 py-1.5 rounded-lg text-red-400 hover:bg-red-50 transition"
                >
                  Delete
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}