import { useState } from 'react'
export default function FollowUps({ followups, addFollowup, updateFollowup, deleteFollowup }) {
  const [showForm, setShowForm] = useState(false)
  const [editId, setEditId] = useState(null)
  const [form, setForm] = useState({
    name: '', company: '', contact: '', followUpDate: '', notes: '', done: false
  })

  function handleChange(e) {
    const value = e.target.type === 'checkbox' ? e.target.checked : e.target.value
    setForm({ ...form, [e.target.name]: value })
  }

  async function handleSubmit() {
    if (!form.name || !form.followUpDate) return
    if (editId !== null) {
      await updateFollowup(editId, form)
      setEditId(null)
    } else {
      await addFollowup(form)
    }
    setForm({ name: '', company: '', contact: '', followUpDate: '', notes: '', done: false })
    setShowForm(false)
  }

  function handleEdit(entry) {
    setForm({
      name: entry.name, company: entry.company, contact: entry.contact,
      followUpDate: entry.followUpDate, notes: entry.notes, done: entry.done
    })
    setEditId(entry.id)
    setShowForm(true)
  }

  async function handleDelete(id) {
    await deleteFollowup(id)
  }

  async function toggleDone(entry) {
    await updateFollowup(entry.id, { ...entry, done: !entry.done })
  }

  function isOverdue(dateStr, done) {
    if (done) return false
    return new Date(dateStr) < new Date(new Date().toDateString())
  }

  const overdue = followups.filter(f => isOverdue(f.followUpDate, f.done))
  const upcoming = followups.filter(f => !isOverdue(f.followUpDate, f.done) && !f.done)
  const completed = followups.filter(f => f.done)

  function renderCard(entry) {
    const overdueFl = isOverdue(entry.followUpDate, entry.done)
    return (
      <div
        key={entry.id}
        className={`bg-white rounded-2xl shadow-sm border p-5 flex items-start justify-between ${overdueFl ? 'border-red-200' : 'border-gray-100'}`}
      >
        <div className="flex gap-4 items-start">
          <input
            type="checkbox"
            checked={entry.done}
            onChange={() => toggleDone(entry)}
            className="mt-1.5 accent-[#e8572a] w-4 h-4 cursor-pointer"
          />
          <div>
            <div className="flex items-center gap-3 mb-1">
              <h3 className={`font-semibold text-lg ${entry.done ? 'line-through text-gray-400' : 'text-[#0f1724]'}`}>
                {entry.name}
              </h3>
              {overdueFl && (
                <span className="text-xs font-medium px-2.5 py-0.5 rounded-full bg-red-100 text-red-600">
                  Overdue
                </span>
              )}
              {entry.done && (
                <span className="text-xs font-medium px-2.5 py-0.5 rounded-full bg-green-100 text-green-600">
                  Done
                </span>
              )}
              {entry.autoGenerated && (
                <span className="text-xs font-medium px-2.5 py-0.5 rounded-full bg-orange-50 text-orange-500">
                  Auto
                </span>
              )}
            </div>
            {entry.company && <p className="text-gray-500 text-sm">{entry.company}</p>}
            {entry.contact && <p className="text-gray-400 text-xs mt-0.5">Contact: {entry.contact}</p>}
            <p className={`text-xs mt-1 font-medium ${overdueFl ? 'text-red-500' : 'text-gray-400'}`}>
              Follow up by: {entry.followUpDate}
            </p>
            {entry.notes && (
              <p className="text-gray-600 text-sm mt-2 bg-gray-50 rounded-lg px-3 py-2">{entry.notes}</p>
            )}
          </div>
        </div>
        <div className="flex gap-2 ml-4 shrink-0">
          <button
            onClick={() => handleEdit(entry)}
            className="text-xs border border-gray-200 px-3 py-1.5 rounded-lg text-gray-500 hover:bg-gray-50 transition"
          >
            Edit
          </button>
          <button
            onClick={() => handleDelete(entry.id)}
            className="text-xs border border-red-100 px-3 py-1.5 rounded-lg text-red-400 hover:bg-red-50 transition"
          >
            Delete
          </button>
        </div>
      </div>
    )
  }

  return (
    <div>
      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-3xl font-bold text-[#0f1724]">Follow-Ups</h1>
          <p className="text-gray-500 mt-1 text-sm">Never miss a follow-up opportunity</p>
        </div>
        <button
          onClick={() => { setShowForm(!showForm); setEditId(null); setForm({ name: '', company: '', contact: '', followUpDate: '', notes: '', done: false }) }}
          className="bg-[#e8572a] text-white px-5 py-2.5 rounded-lg text-sm font-medium hover:bg-[#cf4a20] transition"
        >
          + Add Follow-Up
        </button>
      </div>

      {showForm && (
        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 mb-8">
          <h2 className="text-lg font-semibold text-[#0f1724] mb-4">
            {editId !== null ? 'Edit Follow-Up' : 'New Follow-Up'}
          </h2>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="text-xs font-medium text-gray-500 uppercase tracking-wide">Name</label>
              <input
                name="name"
                value={form.name}
                onChange={handleChange}
                placeholder="e.g. Jane Smith"
                className="mt-1 w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#e8572a]"
              />
            </div>
            <div>
              <label className="text-xs font-medium text-gray-500 uppercase tracking-wide">Company</label>
              <input
                name="company"
                value={form.company}
                onChange={handleChange}
                placeholder="e.g. Shopify"
                className="mt-1 w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#e8572a]"
              />
            </div>
            <div>
              <label className="text-xs font-medium text-gray-500 uppercase tracking-wide">Email / LinkedIn</label>
              <input
                name="contact"
                value={form.contact}
                onChange={handleChange}
                placeholder="e.g. jane@shopify.com or linkedin.com/in/jane"
                className="mt-1 w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#e8572a]"
              />
            </div>
            <div>
              <label className="text-xs font-medium text-gray-500 uppercase tracking-wide">Follow-Up Date</label>
              <input
                name="followUpDate"
                type="date"
                value={form.followUpDate}
                onChange={handleChange}
                className="mt-1 w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#e8572a]"
              />
            </div>
            <div className="col-span-2">
              <label className="text-xs font-medium text-gray-500 uppercase tracking-wide">Notes</label>
              <textarea
                name="notes"
                value={form.notes}
                onChange={handleChange
                }
                placeholder="What do you need to follow up about?"
                rows={3}
                className="mt-1 w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#e8572a]"
              />
            </div>
          </div>
          <div className="flex gap-3 mt-4">
            <button
              onClick={handleSubmit}
              className="bg-[#e8572a] text-white px-5 py-2 rounded-lg text-sm font-medium hover:bg-[#cf4a20] transition"
            >
              {editId !== null ? 'Save Changes' : 'Add Follow-Up'}
            </button>
            <button
              onClick={() => setShowForm(false)}
              className="border border-gray-200 text-gray-500 px-5 py-2 rounded-lg text-sm hover:bg-gray-50 transition"
            >
              Cancel
            </button>
          </div>
        </div>
      )}

      {followups.length === 0 ? (
        <div className="text-center py-20 text-gray-400">
          <p className="text-lg font-medium">No follow-ups yet</p>
          <p className="text-sm mt-1">Click "Add Follow-Up" to start tracking</p>
        </div>
      ) : (
        <div className="flex flex-col gap-8">
          {overdue.length > 0 && (
            <div>
              <h2 className="text-sm font-semibold text-red-500 uppercase tracking-wide mb-3">Overdue</h2>
              <div className="flex flex-col gap-4">{overdue.map(renderCard)}</div>
            </div>
          )}
          {upcoming.length > 0 && (
            <div>
              <h2 className="text-sm font-semibold text-gray-400 uppercase tracking-wide mb-3">Upcoming</h2>
              <div className="flex flex-col gap-4">{upcoming.map(renderCard)}</div>
            </div>
          )}
          {completed.length > 0 && (
            <div>
              <h2 className="text-sm font-semibold text-gray-400 uppercase tracking-wide mb-3">Completed</h2>
              <div className="flex flex-col gap-4">{completed.map(renderCard)}</div>
            </div>
          )}
        </div>
      )}
    </div>
  )
}